### ISSUE TITLE
unable to open YAPF!

### ISSUE THREAD

**Issue by onlystreaks** [blacktop/atom-python-yapf#10]
I'm windows user. Pep8 in my Atom is being used very well, but I just don't know how to use this tool.

**Comment by lexicalunit** [comment]
You'll need to have `yapf` available on your PATH. I don't know how that works in Windows, but once it's there, you should be golden. Alternatively you can provide the exact path to the executable as a configuration option for this package.

**Comment by muratgozel** [comment]
Find yapf.exe file path in your python installation directory and copy the path. Then open "Python Yapf" settings in Atom. Configure Yapf path as "...\Scripts\yapf.exe". In my case this path is "C:\Python27\Scripts\yapf.exe"

**Comment by blacktop** [comment]
@onlystreaks, @lexicalunit and @muratgozel have both contributed great information. I am going to close this issue now.  Feel free to continue to comment if you need more help.

Thank you @lexicalunit and @muratgozel for you help. :+1:
