### ISSUE TITLE
UI Item confusion

### ISSUE THREAD

**Issue by steveoh** [blacktop/atom-python-yapf#11]
What is the significance of ![image](https://cloud.githubusercontent.com/assets/325813/11964017/f01b2b82-a8a7-11e5-822c-317d1fc9a9a7.png)

This is in the task bar of atom and I don't know what it means.

**Comment by blacktop** [comment]
It means that YAPF checked your python and it isn't formatted to yapf's specifications.

**Comment by steveoh** [comment]
maybe an alt/title tag would be in order here.
