### ISSUE TITLE
YAPF:✓ shows no matter what

### ISSUE THREAD

**Issue by LordZane** [blacktop/atom-python-yapf#12]
The YAPF: ✓ shows at all times in the status bar, no matter what file or if no files are open. Can you change it to only show when a python file is opened? (Im using MagicPython instead of the built in language-python, I dont know if this is messing with anything)

EDIT: Only shows the YAPF: ✓ after running YAPF, upon opening a new atom window it is not there

**Comment by blacktop** [comment]
@LordZane you can thank @lexicalunit for this!
