### ISSUE TITLE
can't seem to instal YAPF on OSX

### ISSUE THREAD

**Issue by sergey-ivanchuk** [blacktop/atom-python-yapf#22]
I have 10.11.6 OSX el capitan

I installed YAPF through Atom package handler. In a terminal I can type in "which yapf" and get a directory path, so I have the binary executable at least. I entered that same directory path in my Yapf Path setting, but latter on I get the message "Yapf: unable to open /User/.........".

Anything wrong with my approach ?

**Comment by blacktop** [comment]
what if you leave it blank or just use `yapf`

**Comment by sergey-ivanchuk** [comment]
no luck. The default/blank path creates the comment "YAPF:X" in the bottom of my window.

**Comment by blacktop** [comment]
I am on OSX and when I do a `which yapf` I get: `/usr/local/bin/yapf` you are saying it gives you a /User path?  did you `pip install yapf` ?

**Comment by sergey-ivanchuk** [comment]
yeah, I did `pip install yapf`.

I had yapf 0.16.2 installed in `/Users/my_username/anaconda/bin/yapf`

**Comment by sergey-ivanchuk** [comment]
update : i have YAPF working now. I copied the yapf executable to `/usr/local/bin/yapf`
