### ISSUE TITLE
YAPF doesn't indicate what is incorrect

### ISSUE THREAD

**Issue by MarvBob** [blacktop/atom-python-yapf#26]
When checking code, YAPF is showing the little red cross in the UI to tell me my code doesn't fit its specifications, but I have no idea what is incorrect.
Not really an issue, more an enhancement, but would it be possible to highlight incorrect lines? That red cross is annoying but I don't want to format the whole file without knowing what happened.
I feel like it's a bit weird for a formatter to do kind of a linter's job, but as soon as there is a "check code" function I would appreciate a more detailed check result than that little red cross.

**Comment by blacktop** [comment]
same as #27
