### ISSUE TITLE
YAPF check formatting not reading configuration

### ISSUE THREAD

**Issue by dbarrosop** [blacktop/atom-python-yapf#6]
Hello,
if I run "python-yapf -> Format Code" it works perfectly fine, the code is formatted correctly. However, after formatting, if I do a "python-yapf -> Check formatting" it complains that the format is not correct (in the status bar I can see YAPF: X).

Doing some tests I realize that "Format Code" seems to be reading correctly the style configuration, however "Check Formatting" is using the default. If I fix the code from the CLI without any style defined "python-yapf -> Check formatting" tells me that the format is correct.

This is my style: {based_on_style: google, column_limit: 120}

I am running YAPF 0.2.5, python-yapf 0.7.0 and Atom 1.0.7.

If you need more info or something is unclear let me know.

Thanks!
David

**Comment by blacktop** [comment]
Thank you for this detailed bug report! Much appreciation. :+1:
