### ISSUE TITLE
Can't get it to work on windows

### ISSUE THREAD

**Issue by joaoportela** [blacktop/atom-python-yapf#7]
I have just installed atom and this plugin but I can't get it to work.

I created a file from the example https://github.com/google/yapf#example and the status bar tells me that the file is already ok (http://i.imgur.com/3hTGx4p.png).

Running yapf from the command line works perfectly.

This is my settings page: http://i.imgur.com/0uHeNUz.png

**Comment by ipfans** [comment]
it not works on OSX Atom 1.0.15

**Comment by blacktop** [comment]
Please let me know if that fixed it for you both.  I apologize for the delay.

**Comment by joaoportela** [comment]
Which version should I test with?

**Comment by ipfans** [comment]
I update to v0.9.0, CheckFormat and FormatOnSave still not working.

**Comment by joaoportela** [comment]
Same here.

**Comment by blacktop** [comment]
Can you please tell me:
- OS version
- Python version
- YAPF version

Also is there any other output?  For example a stack trace or output to the console in the DevTools?

**Comment by joaoportela** [comment]
Windows 8.1 Pro.

```
>python --version
Python 2.7.10 :: Anaconda 2.3.0 (64-bit)

>yapf --version
yapf 0.3.0
```

No visible errors. Is there a log file for me to check?

**Comment by ipfans** [comment]
Mac OS X 10.10.5

Python 2.7.10

yapf 0.3.0

No crash stack trace and no outputs in Developer tools console...

**Comment by blacktop** [comment]
@ipfans Did you specify the location of the yapf exe in the settings for the atom plugin?  You are run a set up almost identical to my test setup and it works perfect for me.

**Comment by blacktop** [comment]
@joaoportela I am trying to get a VM with windows on it so I can try and recreate your setup.

**Comment by ipfans** [comment]
@blacktop I used python2.7.10 in pyenv and I also specify the location of the yapf to /Users/kevin/.pyenv/shims/yapf

```
➜  ~  /Users/kevin/.pyenv/shims/yapf --version
yapf 0.3.0
```

It works fine to me. But Atom plugins still not working.

**Comment by joaoportela** [comment]
@blacktop Ok. Say something if you need more info.

**Comment by blacktop** [comment]
@joaoportela what is pylama? do you mean yapf?

**Comment by blacktop** [comment]
@joaoportela I just set up a Windows 10 VM with python 2.7.10 and yapf 0.3 with atom 1.0.19 and it worked great.

**Comment by blacktop** [comment]
@ipfans I install pyenv and used the following:

``` bash
~ ❯❯❯ pyenv which python
/Users/blacktop/.pyenv/versions/2.7.10/bin/python
~ ❯❯❯ pyenv which yapf
/Users/blacktop/.pyenv/versions/2.7.10/bin/yapf
~ ❯❯❯ /Users/blacktop/.pyenv/versions/2.7.10/bin/yapf --version
yapf 0.3.0
```

I am using Atom 1.0.19 and it works perfectly.  I am not sure how to move forward.

The settings I am using in the **atom-python-yapf** are:
![screen shot 2015-09-28 at 11 32 20 pm](https://cloud.githubusercontent.com/assets/6118188/10155990/36df4046-6639-11e5-8b9e-345444a61973.png)

**Comment by joaoportela** [comment]
@blacktop My mistake. Edited it.

**Comment by blacktop** [comment]
@ipfans @joaoportela I recreated the environments you both are using and it worked for me.  This leads me to believe there might be a config issue on your end.  Can you please re confirm that you have a proper path to Yapf?

**Comment by joaoportela** [comment]
I just unistalled python2 on my computer and installed python3 and now yapf works.

For what it's worth: the configs seemed to be correct before.

**Comment by blacktop** [comment]
Ok, I am going to close this issue now.
